/* Generated By:JJTree: Do not edit this line. BSHFactStatement.java */

package bsh;

public class BSHFactStatement extends SimpleNode {
    public BSHFactStatement(int id) {
      super(id);
    }

    public Object eval(CallStack callstack, Interpreter interpreter) throws EvalError {
        System.out.println(((BSHAmbiguousName)jjtGetChild(0)).text);
        for (int i = 1; i < jjtGetNumChildren(); ++i) {
            SimpleNode node = (SimpleNode)jjtGetChild(i);
            System.out.println(node.eval(callstack, interpreter));
        }
        return null;
    }  
}
